# Generated by Django 5.2.4 on 2025-07-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaClone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instapost',
            name='caption',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instapost',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
