# Generated by Django 5.2.4 on 2025-07-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaClone', '0002_alter_instapost_caption_alter_instapost_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='instapost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
